### ISSUE TITLE
Add customization options

### ISSUE THREAD

**Issue by An-anonymous-coder** [umutcamliyurt/MockTraffic#2]
Users should be able to customize things such as:
- The frequency of traffic
This could be a set value such as sending 1 request every 100ms, or a random value such as sending 1 request randomly every 50ms to 1000ms.
- The type of traffic
This could be a set value such as only HTTPS or only DNS, or a random value such as a randomly chosen HTTPS or DNS request. 
- How large the traffic is
This should be a cap on the size limit for each request (e.g. 60MB), and to stop generating traffic after, for example, 5GB total has been generated.
- Which hosts are pinged
This should be a list of hosts (with ports) to ping traffic with, so you can customize whether to only send traffic to www.github.com:443 and www.google.com:80, or send traffic to randomly generated IP addresses. 

There should also be a log listing all of the traffic that was generated.

**Comment by umutcamliyurt** [comment]
I will add these features in future

**Comment by Milkshiift** [comment]
Why was this closed? Currently, the application uses _**a lot**_ of data, and without an ability to customize at least frequency of requests it's unviable on metered connections.

**Comment by Milkshiift** [comment]
Though the frequency is already low, so a possible solution could be an option that disables traffic generation on mobile data (or metered connections in general if android provides an API for that).
Some info:
I've been running MockTraffic for 3 hours, and it has used 140mb of data. Doesn't sound like much, but when extrapolated it's 1120mb in 24 hours, which is 7% percent of my somewhat fancy data plan for just fake data
