### ISSUE TITLE
Requests counter is not functional

### ISSUE THREAD

**Issue by An-anonymous-coder** [umutcamliyurt/MockTraffic#4]
Android 14

The requests counter stays at 0 despite packets being sent (verified with PCAPdroid)

**Comment by umutcamliyurt** [comment]
Reach me at my e-mail please: nemesisuks@protonmail.com

**Comment by umutcamliyurt** [comment]
Issue is not reproducible on my device

**Comment by umutcamliyurt** [comment]
Alright can you give more details about the issue?

**Comment by umutcamliyurt** [comment]
The issue is not reproducible on my device

**Comment by umutcamliyurt** [comment]
I fixed this issue as well :+1:

**Comment by BRBsoup** [comment]
Still happening for me

**Comment by umutcamliyurt** [comment]
Can you give more details about the issue?

**Comment by BRBsoup** [comment]
> Can you give more details about the issue?

The traffic is being generated (I verified) but the Traffic Stats on the UI stays at 0 requests
