### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [umutcamliyurt/MockTraffic#9]
It seems you forgot to [adjust the versioning](https://github.com/umutcamliyurt/MockTraffic/blob/main/app/build.gradle.kts#L13-L14) before making the new release. Other than the "v1.1" suggested by the release tag, the APK still identifies wit 1.0 – and `versionCode` 1. The latter is especially crucial as Android uses it to tell versions apart: whoever had your 1.0 installed, won't receive any update information.

Please always increase `versionCode` and update `versionName` before committing the release. Thanks!

**Comment by IzzySoft** [comment]
PS, while I'm here, the full warning shown by the scanners at IzzyOnDroid was:

```
Binary files /web/ftp/repo/fdroid/repo/com.nemesis.mocktraffic_1.apk and /web/ftp/repo/fdroid/repo/com.nemesis.mocktraffic_1.1.apk differ
! repo/com.nemesis.mocktraffic_1.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

I've explained the first line above. The second one can be avoided with a minor adjustment to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

That said, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link to [your app at IzzyOnDroid](https://apt.izzysoft.de/packages/com.nemesis.mocktraffic) e.g. from your Readme :smiley:

**Comment by umutcamliyurt** [comment]
Fixed this issue

**Comment by IzzySoft** [comment]
Thanks – looks fine now: versioning matches, and the blob is gone :partying_face: Update will roll out with the next sync around 6 pm UTC then.

Mind to add the mentioned badge as well? :smiley:
